### ISSUE TITLE
data-cover attribute on source file is resulting in global failure

### ISSUE THREAD

**Issue by ramkms6666** [alex-seville/blanket#267]
hi, 

I set the data-cover attribute on the src script file as below. 

<script type="text/javascript" charset="UTF-8" src="source.js" data-cover ></script> and it is giving the following error.

too much recursion
Source:     

http://localhost:8001/test/js/blanket.min.js:1

**Comment by milindaddteq** [comment]
i tried something in chrome data-cover is giving the error and  data-cover-flags="debug"  is not giving any error after that run in Firefox working fine. but should check it out why not working in chrome.
