### ISSUE TITLE
Latest merge of development into master broke integration with mocha

### ISSUE THREAD

**Issue by mako-taco** [alex-seville/blanket#369]
fba89cf301d0a6fdf0448e9e868bbcddaae98c36 broke a fix made by 98b25a4f51c69c90713ab175a5f3be2526e16429 by removing this:
```js
BlanketReporter.prototype = mocha._reporter.prototype;
```
Simply adding the line back in to [mocha-adapter.js](https://github.com/alex-seville/blanket/blob/master/src/adapters/mocha-blanket.js) restores functionality.

**Comment by fearphage** [comment]
This issue should be resolved in the development branch.

Use the following in your `package.json` file to refer to the branch as a dependency:

```` javascript 
"blanket": "alex-seville/blanket#development"
````

Please reopen the issue if you're still experiencing problems.
