### ISSUE TITLE
Blanket not working with the latest version of Mocha in the browser

### ISSUE THREAD

**Issue by astorije** [alex-seville/blanket#388]
Hi everyone,

Using the latest [mocha.js][1] (1.17.1, last commit 1 month ago) on the [Mocha in the browser example][2] just shows a blank page.

What needs to be changed in the adapter / HTML markup to make it work again?

Just FYI, this the HTML markup (body only, nothing special in the `head` generated by a recent `mocha init`:

    <div id="mocha"></div>
    <script src="mocha.js"></script>
    <script>mocha.setup('bdd')</script>
    <script src="mylibrary.js"></script>
    <script src="tests.js"></script>
    <script>
      mocha.run();
    </script>

(I also have a call to `chai.js` after loading Mocha that I removed from the example).

Side question: the mocha.css file of the example also differs from the latest [mocha.css][3]. Isnt't it worth using the CSS file provided by Mocha and having a custom CSS file underneath? It would even be nice to have the Blanket box looking like the rest of the Mocha page.

Thanks for the help and for this tool!

[1]: https://github.com/visionmedia/mocha/blob/master/mocha.js
[2]: http://alex-seville.github.io/blanket/test/mocha-browser/adapter.html
[3]: https://github.com/visionmedia/mocha/blob/master/mocha.css

**Comment by fearphage** [comment]
This issue should be resolved in the development branch.

Use the following in your `package.json` file to refer to the branch as a dependency:

```` javascript
"blanket": "alex-seville/blanket#development"
````

Please reopen the issue if you're still experiencing problems.
