### ISSUE TITLE
mocha browser

### ISSUE THREAD

**Issue by R0cKET** [alex-seville/blanket#397]
blanket no tiene soporte para la última versión de mocha v1.18, sólo he logrado hacerla funcionar con la versión 1.13 y blanket v1.1.15

**Comment by fearphage** [comment]
This issue should be resolved in the development branch.

Use the following in your `package.json` file to refer to the branch as a dependency:

```` javascript 
"blanket": "alex-seville/blanket#development"
````

Please reopen the issue if you're still experiencing problems.
