### ISSUE TITLE
Blanket + mocha is blocked in "waiting for blanket..." state when using require.js

### ISSUE THREAD

**Issue by boyander** [alex-seville/blanket#443]
Hi!

I'm having problems on configuring mocha + require + blanket. I'm using grunt-blanket-mocha to run it on phantom.js but i think something is wrong in the mocha adapter. It stops running with "waiting for blanket..." when i run mocha.run() to make the unit-tests start. 
Here's some info:

```
require.config({
        paths: {
            "my-sdk"        : "../lib/my_sdk",
            "mocha"            : "../bower_components/mocha/mocha",
            "my-tests"  : "test-my",
            "chai"             : "../bower_components/chai/chai",
            "blanket"          : "../node_modules/blanket/dist/mocha/blanket_mocha",
        },
        shim: {
            "blanket":{
              deps: ["mocha"]
            }
        }
    });
```

```
require(["mocha","blanket","chai","my-sdk"], function (){
        mocha.setup('bdd');
        if (window.PHANTOMJS) {
            blanket.options("reporter", "../node_modules/grunt-blanket-mocha/support/grunt-reporter.js");
        }
        blanket.options("debug",true);
        require(['my-tests'], function(chai){
          mocha.run();
        });
    });
```

**Comment by fearphage** [comment]
The issue seems to be external to blanket.js itself. However there were mocha integration fixes applied in the development branch.

Use the following in your package.json file to refer to the branch as a dependency:

```` javascript
"blanket": "alex-seville/blanket#development"
````

If that doesn't resolve your issues. I would contact the maintainer of the grunt-blanket-mocha plugin.
