### ISSUE TITLE
global failure (1,0,1) script error Source :0

### ISSUE THREAD

**Issue by przerull** [alex-seville/blanket#471]
When I use blanket.js with QUnit using the file:/// protocol I get a global failure (1,0,1) script error Source :0 showing up on my page, and the file I am trying to perform coverage on shows that 0/0 lines were covered (when the file definitely has lines in it).

Here's a screenshot of the page

![image](https://cloud.githubusercontent.com/assets/304209/6094023/13880df8-aedd-11e4-88cc-7f23682b14c9.png)

Here's a link to the source of the page.  It's in a public mercurial repository on bitbucket.

https://bitbucket.org/przerull/jwidgets/src/238f6dd65776dd3180a1e186d6d78318ca9238b6/tests/index.html?at=default

The coverage works when I run this over http.

Any help here would be greatly appreciated (I really blanket.js in spite of this little issue).

Thank you for your time.

**Comment by alex-seville** [comment]
I think it's because you're running it with the file protocol.  See here for details and workarounds:

https://github.com/alex-seville/blanket/blob/master/docs/special_features.md#local-uploader

**Comment by przerull** [comment]
Yes. That is precisely it.   Thank you so much for your lightning fast response.

**Comment by garex** [comment]
The error is like

`Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///home/ustimenko/git/angular-sorted-map/tests/index.html?hidepassed' cannot be created in a document with origin 'null' and URL 'file:///home/ustimenko/git/angular-sorted-map/tests/index.html'.`
