### ISSUE TITLE
No coverage lines

### ISSUE THREAD

**Issue by settysreekanth** [alex-seville/blanket#472]
@alex-seville  Hi, I am using Blanket for code coverage but I am wondering the syntax for skipping couple of lines in my code coverage? i.e. whats the syntax to exclude code lines from coverage?

**Comment by mansona** [comment]
I think a good way to go about this would be to break your code into a different file and then use data-cover-never to exclude that file.

**Comment by settysreekanth** [comment]
@mansona I was off for a while hence delayed reply . Thanks for your comment.

However, It would be great if we have that no-cover lines feature in blanket; so that we can try to implement 100% coverage eventhough we skip some lines in coverage .

**Comment by settysreekanth** [comment]
This issue is same as #442
