### ISSUE TITLE
publish iojs fixes to npm

### ISSUE THREAD

**Issue by bcoe** [alex-seville/blanket#484]
Would you mind publishing a new version of blanket to npm with the fixes for iojs/mocha?

**Comment by TakenPilot** [comment]
+1, especially now that travis-ci is testing against both nodejs and iojs by default.

**Comment by andrenarchy** [comment]
+1

**Comment by andrenarchy** [comment]
As a workaround you can directly use the current git master in your `package.json` like [here](https://github.com/paperhive/mongoose-authorize/commit/0cbe7fae6ec3a8913b1426dd5d0b1dbf28f72f67).

However, a release would be appreciated! :)

**Comment by bcoe** [comment]
for what it's worth, I've published a module called `patched-blanket` with the fix., I'd rather use the mainline project though:

```"test": "mocha --check-leaks --ui exports --require patched-blanket -R mocoverage",```

**Comment by TakenPilot** [comment]
Heh, it's through/through2 all over again.  Thanks for the [patched-blanket](https://www.npmjs.com/package/patched-blanket).

**Comment by listepo** [comment]
+1

**Comment by alex-seville** [comment]
v1.1.7 has been published

**Comment by alex-seville** [comment]
v1.1.9 has been published too.
