### ISSUE TITLE
A new release please

### ISSUE THREAD

**Issue by madarche** [alex-seville/blanket#488]
The "alternative node.js runtimes for mocha" fix is really useful. It is worth a release just by itself :-)

So could a new release of blanket happen soon please?

I know how to make a dependency on a GitHub commit, but that's OK for private projects it's generally not OK for popular public projects.

Thanks a lot!

**Comment by holyshared** [comment]
+1

**Comment by madarche** [comment]
Please?

**Comment by chrisvdp** [comment]
+1

**Comment by alex-seville** [comment]
v1.1.7 has been created.

**Comment by chrisvdp** [comment]
:tada:

**Comment by madarche** [comment]
Thanks a lot for the v1.1.7 release!
