### ISSUE TITLE
Multiple loaders

### ISSUE THREAD

**Issue by scruffles** [alex-seville/blanket#517]
Our project uses coffeescript and cjsx.  It looks like I should be able to create a custom loader for cjsx that also loads the existing coffeescript loader.  But it seems like this would be an inelegant solution.  It seems like the configuration should accept an array of loaders.  Thoughts?

**Comment by scruffles** [comment]
Is there anything I can do to get this resolved?  Is there a better way to submit my patch (a more active fork)?  Does this conflict with future plans?

**Comment by alex-seville** [comment]
The PR appears to have merge conflicts.  If those are resolved it seems like it could be merged.

**Comment by scruffles** [comment]
ah.  fixed now.
