### ISSUE TITLE
hit color didn't get into 1.1.7 release

### ISSUE THREAD

**Issue by yagni** [alex-seville/blanket#529]
For some reason, the hitcolor fix in commit ee0a8842ea909044d5d499989a38dba7d7d9cd40 didn't make it into the built files in the dist directory. It's definitely in src/qunit/reporter.js, just not in dist/qunit/blanket.js or dist/qunit/blanket.min.js. Just wanted to file an issue in case other things weren't merged into the dist as well.

**Comment by alex-seville** [comment]
Updated built files in 1.1.9
