### ISSUE TITLE
Chrome console ANSI-color issue, with possible CSS solution.

### ISSUE THREAD

**Issue by pmw57** [alex-seville/blanket#533]
Google Chrome's console has a display issue when it comes to ANSI color codes.

Chrome does though allow CSS to style the console, which is documented at https://developers.google.com/web/tools/chrome-devtools/debug/console/console-write#styling-console-output-with-css

For example:

console.log('%cDraw cards: 7 of 7 passed.', 'color: green');

Which could be represented in code as:

console.log('%c' + str, 'color: ' + color);

Is it within the scope of this project to use custom console report logs to help resolve this issue, which has been briefly explored in the following blog post?
https://paulsperambulations.wordpress.com/2015/10/21/blanket-js-ansi-color-workaround-for-chrome-console/

**Comment by alex-seville** [comment]
Yes, if a PR is submitted I think it could be merged into the project.

**Comment by pmw57** [comment]
Thanks Alex - you'll find a bit more than I initially intended in this PR.
https://github.com/alex-seville/blanket/pull/534

I've attempted to make them modular in nature, so that there's no dramatic impact on the reporter.

**Comment by alex-seville** [comment]
Merged.
