### ISSUE TITLE
Breaking change in latest blanket

### ISSUE THREAD

**Issue by dcousens** [alex-seville/blanket#536]
``` javascript
/bitcoinjs-lib/node_modules/blanket/src/index.js:179
                            throw e;
                            ^
Error: BLANKET-Error parsing instrumented code: SyntaxError: Unexpected token (16:6)
```

Invocation: `mocha --require blanket`
On a standard ES5 code base.

Any ideas how to fix?

**Comment by dcousens** [comment]
A relevant TRAVIS CI log: https://travis-ci.org/bitcoinjs/bitcoinjs-lib/jobs/90214117

**Comment by nbiton** [comment]
I experienced a similar issue.
Blanket v1.2.0 is enforcing strict mode on all instrumented code.

I had to revert back to v1.1.9 for now, so the CI server could keep working.

**Comment by dcousens** [comment]
ping @alex-seville ?

**Comment by alex-seville** [comment]
The change was made here:
https://github.com/alex-seville/blanket/pull/530

It could be that setting the ecma script version in the options will fix the issue

**Comment by dcousens** [comment]
@alex-seville setting it to what though? ES5?

**Comment by alex-seville** [comment]
https://github.com/gjurgens/blanket/blob/master/docs/options.md#data-cover-ecmaversion

It's supposed to default to 5, but maybe setting it explicitly would help

**Comment by dcousens** [comment]
``` json
   "config": {
     "blanket": {
      "data-cover-ecmaVersion": 5,
```

Did not resolve the issue.

**Comment by alex-seville** [comment]
If I switch it to 6 it passes. I'm not sure if `acorn` is applying some other restriction that causes it to fail.

**Comment by alex-seville** [comment]
Your code contains a `const`, which is defined in ES6:
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/script.js#L16
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

So, the system works?

**Comment by alex-seville** [comment]
I'm running a PR build now to see if it fixes it:
https://github.com/bitcoinjs/bitcoinjs-lib/pull/502

**Comment by dcousens** [comment]
Thanks @alex-seville,  wouldn't have guessed that.

**Comment by dcousens** [comment]
Might be worth looking into a way to report that error more visibly to maintainers though :+1:.  Again, thanks for the help.

**Comment by alex-seville** [comment]
I'm not sure that there's a way to know that the invalid token is because of a spec issue, but at least this issue might help people diagnose.
