### ISSUE TITLE
Character substitution in blanket code coverage

### ISSUE THREAD

**Issue by slauyama** [alex-seville/blanket#547]
Hi. I'm using blanket 1.2.1 with mocha and I have just got the coverage working but I am now running into an issue that coverage does not display `$` or `'` and instead replaces them with `&dollar;` and `&apos;`. I was looking at the issues on here but couldn't find anything related to it. Is this an known issue or am I doing something wrong with my configuration. The only things I have done is load blanket_mocha (after building it) and adding the `data-cover` attribute to my js file. Any help would be greatly appreciated!

![blanket example](https://cloud.githubusercontent.com/assets/7174954/12028465/71c71a9a-ad8c-11e5-9dca-282b96da3bc2.PNG)

**Comment by uknick** [comment]
I'm getting the same issue when using Blanket (/*! blanket - v1.2.1 */ - built from the latest master branch) with Qunit as the testing framework, I found an older version of Blanket here - http://www.simonveal.com/code-coverage-with-qunit-and-blanket-js/ (v1.1.5) which doesn't have this issue, but has another issue of not highlighting successfully covered code.

So I think there's an issue with it not rendering html entities, and just escaping them?

![qunit](https://cloud.githubusercontent.com/assets/3717469/12169841/ab065380-b533-11e5-9454-996f1d39c7b3.jpg)

Test runner:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>QUnit Example</title>
  <link rel="stylesheet" href="//code.jquery.com/qunit/qunit-1.20.0.css">
</head>
<body>

	<div id="qunit"></div>
	<div id="qunit-fixture"></div>

	<script src="//code.jquery.com/qunit/qunit-1.20.0.js"></script>

	<!-- Blanket v1.2.1 -->
	<script src="blanket.min.js"></script>

	<!-- SRC Scripts -->
	<script src="functions.js" data-cover></script>

	<!-- Test Files-->
	<script src="tests/test1.js"></script>

</body>
</html>
```

**Comment by Gisonrg** [comment]
Found the buggy code [here](https://github.com/alex-seville/blanket/blob/master/src/qunit/reporter.js#L48)
Seems like they escape the '&' char twice so previously escaped result will escape '&' again, and hence cannot be parsed properly in HTML.
For example, `$` will be escaped as `&dollar;`, and they escaped '&' one more time in the end, which caused '&' in `'&dollar;'` to be `'&amp;dollar;'`.

**Comment by slauyama** [comment]
Was able to manually change the blanket_mocha file and it worked. Tried to update to both 1.2.2 and 1.2.3 but ran into other issues. Will report them in another issue.
